import { Approval, Project } from "./types";
import { generateId } from "./utils";

function daysAgo(n: number): string {
  const d = new Date();
  d.setDate(d.getDate() - n);
  return d.toISOString().split("T")[0];
}

function daysFromNow(n: number): string {
  const d = new Date();
  d.setDate(d.getDate() + n);
  return d.toISOString().split("T")[0];
}

export function createDemoData(): { project: Project; approvals: Approval[] } {
  const projectId = generateId();
  const project: Project = {
    id: projectId,
    name: "Ashford Mixed-Use Development",
    createdAt: daysAgo(200),
  };

  const zoningId = generateId();
  const sitePlan1Id = generateId();
  const sitePlan2Id = generateId();
  const env1Id = generateId();
  const env2Id = generateId();
  const env3Id = generateId();
  const trans1Id = generateId();
  const trans2Id = generateId();
  const util1Id = generateId();
  const util2Id = generateId();
  const bldg1Id = generateId();
  const bldg2Id = generateId();
  const bldg3Id = generateId();
  const fireId = generateId();
  const healthId = generateId();

  const approvals: Approval[] = [
    {
      id: zoningId,
      projectId,
      name: "Rezoning Application (C-2 to PUD)",
      category: "zoning",
      agency: "City of Ashford Planning Department",
      status: "under-review",
      assignedTo: "Sarah Chen",
      submissionDate: daysAgo(90),
      expectedDuration: 120,
      actualApprovalDate: null,
      expirationDate: null,
      dependsOn: [],
      notes: "Requires public hearing. City council review expected next month.",
      statusHistory: [
        { date: daysAgo(100), fromStatus: "not-started", toStatus: "in-preparation", note: "Started application" },
        { date: daysAgo(90), fromStatus: "in-preparation", toStatus: "submitted", note: "Submitted to planning dept" },
        { date: daysAgo(75), fromStatus: "submitted", toStatus: "under-review", note: "Assigned to reviewer" },
      ],
      estimatedCost: 15000,
      actualCost: null,
    },
    {
      id: sitePlan1Id,
      projectId,
      name: "Preliminary Site Plan Review",
      category: "site-plan",
      agency: "City of Ashford Development Services",
      status: "in-preparation",
      assignedTo: "Michael Torres",
      submissionDate: null,
      expectedDuration: 45,
      actualApprovalDate: null,
      expirationDate: null,
      dependsOn: [],
      notes: "Awaiting survey completion before submission.",
      statusHistory: [
        { date: daysAgo(60), fromStatus: "not-started", toStatus: "in-preparation", note: "Engaged civil engineer" },
      ],
      estimatedCost: 8500,
      actualCost: null,
    },
    {
      id: sitePlan2Id,
      projectId,
      name: "Final Site Plan Approval",
      category: "site-plan",
      agency: "City of Ashford Development Services",
      status: "comments-received",
      assignedTo: "Michael Torres",
      submissionDate: daysAgo(150),
      expectedDuration: 60,
      actualApprovalDate: null,
      expirationDate: null,
      dependsOn: [zoningId],
      notes: "Reviewer requested additional drainage calculations. OVERDUE.",
      statusHistory: [
        { date: daysAgo(160), fromStatus: "not-started", toStatus: "in-preparation", note: "" },
        { date: daysAgo(150), fromStatus: "in-preparation", toStatus: "submitted", note: "Initial submission" },
        { date: daysAgo(120), fromStatus: "submitted", toStatus: "under-review", note: "" },
        { date: daysAgo(70), fromStatus: "under-review", toStatus: "comments-received", note: "Drainage comments" },
      ],
      estimatedCost: 12000,
      actualCost: null,
    },
    {
      id: env1Id,
      projectId,
      name: "Phase I Environmental Site Assessment",
      category: "environmental",
      agency: "State DEQ",
      status: "approved",
      assignedTo: "Dr. Lisa Park",
      submissionDate: daysAgo(180),
      expectedDuration: 30,
      actualApprovalDate: daysAgo(140),
      expirationDate: daysFromNow(225),
      dependsOn: [],
      notes: "No recognized environmental conditions found.",
      statusHistory: [
        { date: daysAgo(190), fromStatus: "not-started", toStatus: "in-preparation", note: "" },
        { date: daysAgo(180), fromStatus: "in-preparation", toStatus: "submitted", note: "" },
        { date: daysAgo(160), fromStatus: "submitted", toStatus: "under-review", note: "" },
        { date: daysAgo(140), fromStatus: "under-review", toStatus: "approved", note: "Clean report" },
      ],
      estimatedCost: 5000,
      actualCost: 4800,
    },
    {
      id: env2Id,
      projectId,
      name: "NPDES Stormwater Permit",
      category: "environmental",
      agency: "State DEQ",
      status: "under-review",
      assignedTo: "Dr. Lisa Park",
      submissionDate: daysAgo(45),
      expectedDuration: 90,
      actualApprovalDate: null,
      expirationDate: null,
      dependsOn: [],
      notes: "Stormwater pollution prevention plan included.",
      statusHistory: [
        { date: daysAgo(60), fromStatus: "not-started", toStatus: "in-preparation", note: "" },
        { date: daysAgo(45), fromStatus: "in-preparation", toStatus: "submitted", note: "" },
        { date: daysAgo(30), fromStatus: "submitted", toStatus: "under-review", note: "" },
      ],
      estimatedCost: 3500,
      actualCost: null,
    },
    {
      id: env3Id,
      projectId,
      name: "Wetlands Delineation & Mitigation Plan",
      category: "environmental",
      agency: "US Army Corps of Engineers",
      status: "in-preparation",
      assignedTo: "Dr. Lisa Park",
      submissionDate: null,
      expectedDuration: 120,
      actualApprovalDate: null,
      expirationDate: null,
      dependsOn: [],
      notes: "Wetland boundary survey in progress.",
      statusHistory: [
        { date: daysAgo(30), fromStatus: "not-started", toStatus: "in-preparation", note: "Hired wetland consultant" },
      ],
      estimatedCost: 25000,
      actualCost: null,
    },
    {
      id: trans1Id,
      projectId,
      name: "Traffic Impact Analysis",
      category: "transportation",
      agency: "County DOT",
      status: "comments-received",
      assignedTo: "James Wright",
      submissionDate: daysAgo(130),
      expectedDuration: 45,
      actualApprovalDate: null,
      expirationDate: null,
      dependsOn: [sitePlan2Id],
      notes: "DOT requested additional intersection analysis. OVERDUE.",
      statusHistory: [
        { date: daysAgo(140), fromStatus: "not-started", toStatus: "in-preparation", note: "" },
        { date: daysAgo(130), fromStatus: "in-preparation", toStatus: "submitted", note: "" },
        { date: daysAgo(100), fromStatus: "submitted", toStatus: "under-review", note: "" },
        { date: daysAgo(60), fromStatus: "under-review", toStatus: "comments-received", note: "Additional data needed" },
      ],
      estimatedCost: 18000,
      actualCost: null,
    },
    {
      id: trans2Id,
      projectId,
      name: "Driveway Access Permit",
      category: "transportation",
      agency: "County DOT",
      status: "not-started",
      assignedTo: "James Wright",
      submissionDate: null,
      expectedDuration: 30,
      actualApprovalDate: null,
      expirationDate: null,
      dependsOn: [sitePlan2Id],
      notes: "Cannot begin until site plan is finalized.",
      statusHistory: [],
      estimatedCost: 2000,
      actualCost: null,
    },
    {
      id: util1Id,
      projectId,
      name: "Water & Sewer Availability Letter",
      category: "utility",
      agency: "Ashford Water Authority",
      status: "submitted",
      assignedTo: "Karen Phillips",
      submissionDate: daysAgo(20),
      expectedDuration: 14,
      actualApprovalDate: null,
      expirationDate: null,
      dependsOn: [sitePlan1Id],
      notes: "Routine availability confirmation.",
      statusHistory: [
        { date: daysAgo(25), fromStatus: "not-started", toStatus: "in-preparation", note: "" },
        { date: daysAgo(20), fromStatus: "in-preparation", toStatus: "submitted", note: "" },
      ],
      estimatedCost: 500,
      actualCost: null,
    },
    {
      id: util2Id,
      projectId,
      name: "Electrical Service Application",
      category: "utility",
      agency: "Regional Power Co-op",
      status: "in-preparation",
      assignedTo: "Karen Phillips",
      submissionDate: null,
      expectedDuration: 30,
      actualApprovalDate: null,
      expirationDate: null,
      dependsOn: [sitePlan2Id],
      notes: "Load calculations pending from MEP engineer.",
      statusHistory: [
        { date: daysAgo(15), fromStatus: "not-started", toStatus: "in-preparation", note: "" },
      ],
      estimatedCost: 1500,
      actualCost: null,
    },
    {
      id: bldg1Id,
      projectId,
      name: "Building Permit – Core & Shell",
      category: "building",
      agency: "City of Ashford Building Division",
      status: "not-started",
      assignedTo: "David Kim",
      submissionDate: null,
      expectedDuration: 90,
      actualApprovalDate: null,
      expirationDate: null,
      dependsOn: [zoningId, sitePlan2Id],
      notes: "Structural drawings in progress.",
      statusHistory: [],
      estimatedCost: 45000,
      actualCost: null,
    },
    {
      id: bldg2Id,
      projectId,
      name: "Building Permit – Residential Interiors",
      category: "building",
      agency: "City of Ashford Building Division",
      status: "not-started",
      assignedTo: "David Kim",
      submissionDate: null,
      expectedDuration: 60,
      actualApprovalDate: null,
      expirationDate: null,
      dependsOn: [zoningId, sitePlan2Id],
      notes: "Awaiting unit layout finalization.",
      statusHistory: [],
      estimatedCost: 30000,
      actualCost: null,
    },
    {
      id: bldg3Id,
      projectId,
      name: "Building Permit – Retail Tenant Improvements",
      category: "building",
      agency: "City of Ashford Building Division",
      status: "not-started",
      assignedTo: "David Kim",
      submissionDate: null,
      expectedDuration: 45,
      actualApprovalDate: null,
      expirationDate: null,
      dependsOn: [zoningId, sitePlan2Id],
      notes: "Tenant mix not yet confirmed.",
      statusHistory: [],
      estimatedCost: 20000,
      actualCost: null,
    },
    {
      id: fireId,
      projectId,
      name: "Fire Marshal Plan Review",
      category: "fire-life-safety",
      agency: "Ashford Fire Department",
      status: "not-started",
      assignedTo: "Rachel Adams",
      submissionDate: null,
      expectedDuration: 30,
      actualApprovalDate: null,
      expirationDate: null,
      dependsOn: [bldg1Id],
      notes: "Fire access road and hydrant placement to be reviewed.",
      statusHistory: [],
      estimatedCost: 3000,
      actualCost: null,
    },
    {
      id: healthId,
      projectId,
      name: "Food Service Establishment Permit",
      category: "health",
      agency: "County Health Department",
      status: "in-preparation",
      assignedTo: "Tom Baker",
      submissionDate: null,
      expectedDuration: 21,
      actualApprovalDate: null,
      expirationDate: null,
      dependsOn: [],
      notes: "Required for ground-floor restaurant tenant.",
      statusHistory: [
        { date: daysAgo(10), fromStatus: "not-started", toStatus: "in-preparation", note: "Kitchen plans being drafted" },
      ],
      estimatedCost: 1200,
      actualCost: null,
    },
  ];

  return { project, approvals };
}
